### ISSUE TITLE
Can't seem to login, no errors are returned.

### ISSUE THREAD

**Issue by MarkTierney1975** [CallMeNP/lara-auth-bridge#10]
Hi does this package work with Laravel 5.1?

When I try to log in it doesn't seem to be creating a new cookie here. The $matches array is always empty even though it is finding the user in the database.

```
function curlResponseHeaderCallback($ch, $headerLine) {
    preg_match_all('/^Set-Cookie:\s*([^;]*)/mi', $headerLine, $matches);
    foreach($matches[1] as $item) {
        parse_str($item, $cookie);
        setcookie(key($cookie), $cookie[key($cookie)], time() + 86400, "/");
    }

    return strlen($headerLine); // Needed by curl
}
```

**Comment by MarkTierney1975** [comment]
I'm testing this locally btw.

**Comment by Bukashk0zzz** [comment]
Hi, 
Package working. I tested it with Laravel 5.1 and Laravel 5.0

PHPBB is on same domain?

**Comment by MarkTierney1975** [comment]
Yes, same domain in a subfolder.

**Comment by Bukashk0zzz** [comment]
Not sure how can I help you. This module now works in production with laravel 5.1 and all ok. 
Need more info about your setup. 

Do you change url in config?
If you login in laravel do you auth in phpbb?

**Comment by MarkTierney1975** [comment]
Hi no worries, I've had to move on and use something else so I've not got it installed to test anymore. 

From memory I couldn't login to the forums either via Laravel auth or using the forum login. I followed the installation instructions and changed the url, set the key etc.

**Comment by Bukashk0zzz** [comment]
So I close the issue then. If you had new info I will reopen it.
