### ISSUE TITLE
is this still not work with phpbb 3.1 ?

### ISSUE THREAD

**Issue by anonprophet** [CallMeNP/lara-auth-bridge#5]
can i use this for phpbb 3.1 ?

**Comment by CallMeNP** [comment]
this not work. need write another one.

phpbb3.0 https://wiki.phpbb.com/Authentication_plugins
phpbb3.1 https://wiki.phpbb.com/Authentication_providers

**Comment by Bukashk0zzz** [comment]
Updated to support 3.1

Old version on brunch 3.0

**Comment by CallMeNP** [comment]
So quickly! Awesome!
Can we put the code in same branch?
e.g.

```
/phpbb3.0/
/phpbb3.1/
/src/
/README.md
```

What do you think? @Bukashk0zzz

**Comment by Bukashk0zzz** [comment]
Yes. We can.

**Comment by anonprophet** [comment]
thanks, but when `composer require callmenp/lara-auth-bridge`
i cant find `phpbb3.1`
only `phpbb3.0` 

sorry for noob question

**Comment by CallMeNP** [comment]
@anonprophet try again. :- )
