### ISSUE TITLE
Cant connect laravel with phpbb

### ISSUE THREAD

**Issue by anonprophet** [CallMeNP/lara-auth-bridge#6]
im already try install using instruction

my laravel website using username to login , im already login in my laravel web, when open phpbb its not login

![laravel5_2](https://cloud.githubusercontent.com/assets/8217350/10121488/62a5e986-6518-11e5-96eb-55c820157d0b.png)
![laravel5_3](https://cloud.githubusercontent.com/assets/8217350/10121489/65943e72-6518-11e5-9791-0353e594b489.png)

**Comment by Bukashk0zzz** [comment]
Forum and laravel project on same domain?

Autologin will works only if they are on the same domain because of cookie policy.

**Comment by anonprophet** [comment]
ya 
laravel in `http://laravel5.dev`
phpbb in `http://laravel5.dev/forum`

do i miss something ?

**Comment by Bukashk0zzz** [comment]
Looks all correct. What happens when you login at forum manually?

**Comment by Bukashk0zzz** [comment]
Also what you see when open http://laravel5.dev/auth-bridge/login in browser?

**Comment by anonprophet** [comment]
when login manually from phpbb using `anonprophet` its always say 
`You have specified an incorrect username. Please check your username and try again.`

http://laravel5.dev/auth-bridge/login only white blank space

**Comment by Bukashk0zzz** [comment]
> http://laravel5.dev/auth-bridge/login only white blank space

This is the problem. Do you sure that you add provider 
'providers' => array(
    'CallMeNP\LaraAuthBridge\LaraAuthBridgeServiceProvider',
);

And maybe you use multi auth?   What function do you use for getting user data? Auth::client()->user() or Auth::user() ?

**Comment by anonprophet** [comment]
im already add it, but little change `::class` using 5.1
![lara](https://cloud.githubusercontent.com/assets/8217350/10129827/c7c914d0-65ec-11e5-8e66-f33575fc4af8.png)

im use `Auth::user()`

**Comment by Bukashk0zzz** [comment]
I can help you without debuging your case.

You have problem in https://github.com/CallMeNP/lara-auth-bridge/blob/master/src/CallMeNP/LaraAuthBridge/Controllers/ApiController.php 

Metod getSession()  have to return your current session but this not happens. You can debug why this happens. Also maybe you have some php errors in server logs?

**Comment by anonprophet** [comment]
already set debug mode to true

check php error log only got this when access /auth-bridge/login

`[28-Sep-2015 08:51:38 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\laravel5\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 2710`

**Comment by Bukashk0zzz** [comment]
So thats a problem. 

If you do not have access to your php.ini file (and your webhost allows it), you can override the memory allocation through your .htaccess file. Add php_value memory_limit 512M (or whatever your desired allocation is).

**Comment by anonprophet** [comment]
sure i have access, im develop in my local PC using XAMPP
im already change the value in php.ini to 256M and 512M but its not help.

```
[28-Sep-2015 08:57:36 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\laravel5\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 2710

[28-Sep-2015 08:59:06 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\laravel5\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 2710
```

**Comment by Bukashk0zzz** [comment]
What exactly Laravel version do you have?

**Comment by anonprophet** [comment]
Laravel 5.1.X

![lara2](https://cloud.githubusercontent.com/assets/8217350/10131423/5518cb34-65fa-11e5-8a17-141f1080c9e6.png)

**Comment by Bukashk0zzz** [comment]
Have the same configuration and all works. Try to find on what exactly point this happens. 

I mean this error happens when php run LaraAuthBridge/Controllers/ApiController.php file or not.

**Comment by anonprophet** [comment]
can i get ur email ?

**Comment by Bukashk0zzz** [comment]
Also try to put dd(Auth::user());die(); in first row of getSession method. 

Skype: bukashk0z

**Comment by anonprophet** [comment]
i got this when dd

```
User {#221 ▼
  #table: "users"
  #fillable: array:5 [▶]
  #hidden: array:2 [▶]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:9 [▶]
  #original: array:9 [▶]
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
}
```

**Comment by Bukashk0zzz** [comment]
Skype.

**Comment by msyadav88** [comment]
Hi, I am also facing the same problem. Means After getting login and then when autologin() is called it is not getting true for Auth::check() in getseesion api.
