### ISSUE TITLE
You were not logged out, as the request did not match your session. Please contact the board administrator if you continue to experience problems.

### ISSUE THREAD

**Issue by anonprophet** [CallMeNP/lara-auth-bridge#7]
i got this, after first login using Dotabattle (uppercase D)

everytime i want logout from phpbb i got this error

```
You were not logged out, as the request did not match your session. Please contact the board administrator if you continue to experience problems.
```

i think its case sensitive
i fix this with change phpbb user tabble `username` coulumn and lowered that in database

**Comment by Bukashk0zzz** [comment]
fixed
