### ISSUE TITLE
CSRF Token mismatch

### ISSUE THREAD

**Issue by ghost** [CallMeNP/lara-auth-bridge#8]
Hey there, good work! Unfortunately on L5.1 when you the phpBB extension tries to POST the laravel website, it return CSRF token mismatch. The reason is the middlewere -\App\Http\Middleware\VerifyCsrfToken::class which is applied on every request. So that's why it won't work, unless the middleware is commented out of the app/Http/Kernel.php or if you modify the VerifyCsrfToken.php file.
Can you please confirm that this is the reason and may be add this to the readme?

**Comment by Bukashk0zzz** [comment]
You are correct. Problem in VerifyCsrfToken.php file. I added to readme this.
Thanks for issue.
