### ISSUE TITLE
October cms

### ISSUE THREAD

**Issue by boyfromhell** [CallMeNP/lara-auth-bridge#9]
so it can be used with octobercms?
and if so can you give a small example how.
thank you.

**Comment by Bukashk0zzz** [comment]
You can try)

But it developed for native laravel auth. If octobercms used it all will work.

**Comment by boyfromhell** [comment]
For authentication using this plugin.
https://github.com/rainlab/user-plugin

**Comment by Bukashk0zzz** [comment]
Can you just try this bridge?) If something will not work I will try to fix.
